### ISSUE TITLE
Implement search function/interface

### ISSUE THREAD

**Issue by WolfgangEibner** [backmeup/backmeup-frontend#10]

**Comment by fetzig** [comment]
"no description given"....still waiting for info
(reminder: the search doesn't work on dev01, as far as my understanding goes. should have gotten infos/detailed docu last week)

**Comment by WolfgangEibner** [comment]
There was an issue created by fschoeppl one week ago (49 in backmeup-prototype) regarding the search function. Please be so kind to regularly look at the newsfeed/issue list because github is not sending e-mails in all situations and also a human mistake in issue assignment can occur from time to time.
