### ISSUE TITLE
Index: Deactivate and maybe delete index in UI

### ISSUE THREAD

**Issue by WolfgangEibner** [backmeup/backmeup-frontend#17]
Global activation/deactivation of index - rather than per job. Delete index if user confirms it at deactivation.

See backmeup/backmeup-prototype#55 for details.

**Comment by fetzig** [comment]
api still doesn't return list of existing/settable properties. or a list of existing properties to hardcode it into the frontend settings (hope i don't need to explain the drawbacks...)

(rather have an api call to set/get all/multiple properties instead of set/get single property)

**Comment by fetzig** [comment]
how to delete the index?

**Comment by WolfgangEibner** [comment]
/users/{username}/deleteIndex
REST API Doc
