### ISSUE TITLE
Search-filter datasource should use datasource profile + name

### ISSUE THREAD

**Issue by WolfgangEibner** [backmeup/backmeup-frontend#27]
E.g. Facebook (Wolfgang Eibner) and not org.backmeup.facebook. It also seems that only the type of datasource is indexed/filtered and not the specific profile (Facebook profile of Wolfgang Eibner).

Same thing at search result details with datasource/datasink.

**Comment by fetzig** [comment]
as far as i understand this isn't possible with the current filter options of the api response.

should work without further updates in the frontend as soon as the options are served by the api.

**Comment by WolfgangEibner** [comment]
Should be fixed backmeup/backmeup-prototype@3ac1e48aa38f8774e522204e358a59e8352c7879.

**Comment by WolfgangEibner** [comment]
... and finally in backmeup/backmeup-prototype@ee267bf790b85c8206f631272749371076a3ce28
