### ISSUE TITLE
search filter doesn't work

### ISSUE THREAD

**Issue by fetzig** [backmeup/backmeup-frontend#32]
couldn't find any documentation but the frontend filters by sending following request:

``` javascript
// [GET] http://bmu-dev01.x:8080/backups/test_bmu_1@fetzig.at/90/query/
request params: {
  "source": "org.backmeup.moodle"
}
```

response is equal to not sending "filter" params:

``` javascript
{
  "files": [
    // results...
  ], 
  "progress": 0, 
  "searchQuery": "test", 
  "bySource": [
    {
      "count": 1, 
      "title": "org.backmeup.moodle"
    }, 
    {
      "count": 2, 
      "title": "org.backmeup.twitter"
    }
  ], 
  "byType": [
    {
      "count": 1, 
      "title": "image"
    }, 
    {
      "count": 2, 
      "title": "html"
    }
  ]
}
```

this doesn't work (obviously). how should the filter work?

**Comment by WolfgangEibner** [comment]
Should be fixed in backmeup/backmeup-prototype@98c13e57bd4ef282f88d1fc64915d2b47e3742f6

**Comment by WolfgangEibner** [comment]
Request from UI:
[GET] http://localhost:8080/backups/we@x-net.at/15/query/
request params: {
   "source": "org.backmeup.facebook (Wolfgang Eibner)", 
   "type": "image"
}

Wrong parameter names or simply ignored/not implemented?

**Comment by keros** [comment]
In my tests it works fine now. Please make more tests.
