### ISSUE TITLE
Search results and search result details

### ISSUE THREAD

**Issue by WolfgangEibner** [backmeup/backmeup-frontend#33]
We should show more details at search result details:
- path in backup (key/value "destination" in "properties")
- last modification of item in Facebook/Twitter/... (key/value "modified" in "properties", optional)
- creation date of item in Facebook/Twitter/... (key/value "created" in "properties", optional)
- "Erstellt am" seems to be backup timestamp ("timeStamp") and should therefor be named "Gesichert am"
- search detail page offers no way to get back to search results (beside from browsers history back button), maybe link "Suche" image at top left to navigate back.

At search results:
- maybe we should show created/modified date if existent and not only backup-timestamp.

Search results:
![bildschirmfoto vom 2013-07-12 09 46 43](https://f.cloud.github.com/assets/1263318/786810/38e19852-eac7-11e2-8f36-c526918ea3a5.png)

Search details:
![bildschirmfoto vom 2013-07-12 09 43 34](https://f.cloud.github.com/assets/1263318/786801/f494eed8-eac6-11e2-827f-4e5f0a9e67a2.png)

Snippet of REST response for one item:
        {
            "datasource": "org.backmeup.facebook (Wolfgang Eibner)", 
            "fileId": "1:1e6addadf5f50c303e2769dc0c613f3c:1373538696766", 
            "jobName": "FB->ZIP, Photos+Profile 3, 11.07.13", 
            "properties": [
                {
                    "key": "tags", 
                    "value": "Wolfgang Eibner "
                }, 
                {
                    "key": "source", 
                    "value": "facebook"
                }, 
                {
                    "key": "likes", 
                    "value": "Alexander Steiner, Werner Dreer"
                }, 
                {
                    "key": "backup_sink", 
                    "value": "org.backmeup.zip - Profil"
                }, 
                {
                    "key": "path", 
                    "value": "/Alben/Fotos/109096685781823.jpg"
                }, 
                {
                    "key": "parent", 
                    "value": "109096499115175"
                }, 
                {
                    "key": "modified", 
                    "value": "29.03.2010 14:50:53 MESZ"
                }, 
                {
                    "key": "destination", 
                    "value": "Alben/Fotos/109096685781823.jpg"
                }, 
                {
                    "key": "file_md5_hash", 
                    "value": "1e6addadf5f50c303e2769dc0c613f3c"
                }
            ], 
            "thumbnailUrl": "thumbnails/we@x-net.at/1:1e6addadf5f50c303e2769dc0c613f3c:1373538696766", 
            "timeStamp": 1373538696766, 
            "title": "109096685781823.jpg", 
            "type": "image"
        },

**Comment by WolfgangEibner** [comment]
See also  backmeup/backmeup-prototype#102.

**Comment by carina21** [comment]
seems to be fixed
