### ISSUE TITLE
Menu entries (Wording, link to ZIP Archives)

### ISSUE THREAD

**Issue by WolfgangEibner** [backmeup/backmeup-frontend#35]
"Meine Backups" should maybe be "Meine Backup-Jobs"/"Meine Backup Aufträge" as it doesn't contain the backups itself.

"Zip-Archiv" link could be removed from the bottom of the page and added to the users menu at the top.

**Comment by fetzig** [comment]
@bdf-net any feedback?

**Comment by carina21** [comment]
seems to be fixed
