### ISSUE TITLE
Unicode/display error for Umlaute if not in search term

### ISSUE THREAD

**Issue by WolfgangEibner** [backmeup/backmeup-frontend#39]
Suchbegriff "Kübel":

![bildschirmfoto vom 2013-07-12 14 50 32](https://f.cloud.github.com/assets/1263318/788067/df39df00-eaf1-11e2-8044-093abc647e8a.png)

```
"preview": "... Fest <em>K\u00fcbel</em> ^^  \t \tUnser neuester Kitsch ^^  \t \tZwei Pilotensch\u00fcler beim Flieger basteln...  \t \tNe ..."
```

Suchbegriff "Flieger":

![bildschirmfoto vom 2013-07-12 14 52 49](https://f.cloud.github.com/assets/1263318/788081/5aec15fa-eaf2-11e2-94c7-ccdb720b4426.png)

```
"preview": "... Fest K\u00fcbel ^^  \t \tUnser neuester Kitsch ^^  \t \tZwei Pilotensch\u00fcler beim <em>Flieger</em> basteln...  \t \tNe ..."
```

**Attention: Only remembering this issue. Preview and picture in second case don't match. At this time we have a Umlaut-Bug in Facebook again which prevents me from getting the right test cases.**

**Comment by carina21** [comment]
Fehler bei Detail-Ansicht
![bildschirmfoto vom 2013-07-19 09 04 52](https://f.cloud.github.com/assets/5031128/824318/aafab6b0-f041-11e2-8dc5-cf1bb8d378a1.png)
![bildschirmfoto vom 2013-07-19 09 06 42](https://f.cloud.github.com/assets/5031128/824329/d1a09460-f041-11e2-85fa-f411df722137.png)
