### ISSUE TITLE
Change back to old E-Mail address does not work

### ISSUE THREAD

**Issue by keros** [backmeup/backmeup-frontend#5]
1. Step:
   Created an new account "ft@x-net.at"
   Activate Account (E-Mail)
2. Step:
   Changed E-Mail address (username) in the account settings to "irgend@x-net.at".
   Activated Account (E-Mail)
3.  Step:
   Try to change back to the original E-Mail address "ft@x-net.at"
   If I open the account settings I see my old E-Mail address "ft@x-net.at". But the new one "irgend@x-net.at" should be in the text box.
   If I try to change the E-Mail address to "ft@x-net.at" and save this nothing happens.

If I try to set the "irgend@x-net.at" again this works. I get an new verification mail and have to reverify my account.

**Comment by fetzig** [comment]
can't reproduced. seems to be fixed. please close, if so.

**Comment by keros** [comment]
The problem still exists. Its not possible to change back to my old Mail address.

1)
Create an new account with "ft@x-net.at"
activated the account (E-Mail)

2)
Login to Account with username "ft@x-net.at"
Go to "Einstellungen". Here I can see the following:
- Text Box "E-mail" with "ft@x-net.at" inserted.
- Text Box "Neues Passwort" blank.
- Text Box "Neues Passwort wiederholen" blank.
- Text Box "Bestehendes Passwort" blank.

3)
Changed the address in the "E-Mail" text box to "test@x-net.at"
Inserted "Neues Passwort", "Neues Passwort wiederholen" and "Bestehendes Passwort" (I used 3 times the same value. I don't would change my password).
Pressed the "speichern" button.
Logout from the account.

4)
Activated the account with the new E-Mail I got on "test@x-net.at".

5)
Login to Account with username "test@x-net.at".
Go to "Einstellungen". Here I can see the following:
- Text Box "E-mail" with "ft@x-net.at" inserted.
- Text Box "Neues Passwort" blank.
- Text Box "Neues Passwort wiederholen" blank.
- Text Box "Bestehendes Passwort" blank.

This is wrong. The text box "E-mail " should show me "test@x-net.at" and not "ft@x-net.at".
If I now enter values in the password fields and press the "speichern" button nothing happens.
I don't get a new registration E-Mail to "ft@x-net.at".
It is also not possible to login with "ft@x-net.at" as username ("Benutzername und Passwort stimmen nicht überein. Bitte versuchen Sie es erneut.")

**Comment by fetzig** [comment]
> The problem still exists. Its not possible to change back to my old Mail address.

still can't reproduce...seems like you forget to "activate" the new email address.

> 3)
> ...
> I don't would change my password).

"new password" is no required field.

> 4)
> Activated the account with the new E-Mail I got on "test@x-net.at".

are you sure? only way to reproduce your bug is to not activate the new email.

> If I now enter values in the password fields and press the "speichern" button nothing happens.

nothing happens? guess you mean the response after submitting the form has no success/error message.
- so i made sure error messages are delivered to the end user
- but can't add success message (rest api response is 204 if successful)

**Comment by keros** [comment]
> > The problem still exists. Its not possible to change back to my old Mail address.
> 
> still can't reproduce...seems like you forget to "activate" the new email address.

I have definitly activated the new E-Mail adress. Else I would have get the "User not activated" arror message on the home screen.

> > 3)
> > ...
> > I don't would change my password).
> 
> "new password" is no required field.

I missunderstood the error message here. Only the old password field is required.

> > 4)
> > Activated the account with the new E-Mail I got on "test@x-net.at".
> 
> are you sure? only way to reproduce your bug is to not activate the new email.

Yes

But I can't reproduce it now because I get an error Message if I try to change my E-Mail address.
TypeError at /user_settings/
....

**Comment by fetzig** [comment]
fixed TypeError

**Comment by fetzig** [comment]
could be reproduced (finally), and fixed. thx.
