### ISSUE TITLE
Reuse existing datasource/-sink profiles in new job

### ISSUE THREAD

**Issue by WolfgangEibner** [backmeup/backmeup-frontend#8]
At creating a new job existing datasource/-sink profiles should be shown to user, so that he can choose one of them.

As far as I understood all necessary REST calls exists and it is only a UI issue.

**Comment by fetzig** [comment]
sadly still not the case, need the account identifier (username, email) of the datasource/-sink account in the rest api's response of datasources/{username}/profiles.

this makes not much sense for the enduser, no matter how formated:

``` javascript
{
title: "org.backmeup.facebook - Profil",
createDate: 1351526514741,
modifyDate: 1351526514741,
pluginName: "org.backmeup.facebook",
datasourceProfileId: 58
},
{
title: "org.backmeup.dropbox - Profil",
createDate: 1351527121508,
modifyDate: 1351527121508,
pluginName: "org.backmeup.dropbox",
datasourceProfileId: 59
},
{
title: "org.backmeup.moodle - Profil",
createDate: 1351528517258,
modifyDate: 1351528517258,
pluginName: "org.backmeup.moodle",
datasourceProfileId: 61
},
{
title: "org.backmeup.moodle - Profil",
createDate: 1351528783660,
modifyDate: 1351528783660,
pluginName: "org.backmeup.moodle",
datasourceProfileId: 62
}
```

**Comment by WolfgangEibner** [comment]
So it depends on issue 65 in backmeup-prototype ("Save user identification from datasources/-sinks").

**Comment by WolfgangEibner** [comment]
...which should be nearly fixed right now.
